# Generated by Django 3.2.8 on 2021-11-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
                ('hp_c', models.FloatField(default=0.001)),
                ('train_score', models.FloatField()),
                ('test_score', models.FloatField()),
                ('train_date', models.DateTimeField(verbose_name='date trained')),
            ],
        ),
    ]
